import { PMTiles } from 'https://cdn.jsdelivr.net/npm/pmtiles@4.4.1/+esm';
import { VectorTile } from 'https://cdn.jsdelivr.net/npm/@mapbox/vector-tile@2.0.4/+esm';
import Pbf from 'https://cdn.jsdelivr.net/npm/pbf@4.0.1/+esm';

const V = window.Vietflex;
const ANHMAP_SNAPSHOT = 'https://cdn.jsdelivr.net/gh/Vietflexmap/anhmap@e80f4ee9f1e167817e4a9af8402c0bca4052573e/index.html';
const SOURCE_LAYER = 'admin';
const $ = (id) => document.getElementById(id);
const fmt0 = new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0});
const fmt2 = new Intl.NumberFormat('vi-VN',{maximumFractionDigits:2});
const state = {data:null,units:[],provinces:[],selected:null,boundary:null,boundaryRecords:[],boundaryByKey:new Map(),compareMode:'province',compareMetric:'area_km2',compareItems:[],chart:null};

function normalize(text='') { return text.toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(); }
function unitKey(name,type,province){ return `${normalize(province)}|${normalize(type)}|${normalize(name)}`; }
function n(v,d=0){return v==null||Number.isNaN(Number(v))?'—':(d?fmt2:fmt0).format(Number(v));}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

class MemorySource {
  constructor(bytes){this.bytes=bytes;this.key=`memory://vietflex-admin-${bytes.byteLength}`;}
  getKey(){return this.key;}
  async getBytes(offset,length){const view=this.bytes.subarray(offset,offset+length);return {data:view.buffer.slice(view.byteOffset,view.byteOffset+view.byteLength)};}
}
function decodeBase64(text){const clean=text.replace(/\s+/g,'');const binary=atob(clean);const bytes=new Uint8Array(binary.length);const chunk=32768;for(let o=0;o<binary.length;o+=chunk){const end=Math.min(o+chunk,binary.length);for(let i=o;i<end;i++)bytes[i]=binary.charCodeAt(i);}return bytes;}
function pointInRing(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];const hit=(a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y||Number.EPSILON)+a.x;if(hit)inside=!inside;}return inside;}
function pointInGeometry(x,y,geometry){let inside=false;for(const ring of geometry)if(ring.length>2&&pointInRing(x,y,ring))inside=!inside;return inside;}

class BoundaryLayer extends V.GridLayer {
  initialize(archive,options={}){super.initialize({tileSize:256,minZoom:4,maxZoom:18,minNativeZoom:4,maxNativeZoom:9,noWrap:true,updateWhenIdle:false,keepBuffer:2,className:'boundary-canvas',...options});this.archive=archive;this.decoded=new Map();this.selectedIds=new Set();}
  async _getDecodedTile(z,x,y){const key=`${z}/${x}/${y}`;if(!this.decoded.has(key)){this.decoded.set(key,this.archive.getZxy(z,x,y).then(result=>{if(!result)return[];const vt=new VectorTile(new Pbf(new Uint8Array(result.data)));const layer=vt.layers[SOURCE_LAYER];if(!layer)return[];const out=[];for(let i=0;i<layer.length;i++){const f=layer.feature(i);if(f.type!==3)continue;out.push({properties:f.properties||{},geometry:f.loadGeometry(),extent:layer.extent||4096});}return out;}));}return this.decoded.get(key);}
  createTile(coords,done){const tile=document.createElement('canvas');const ratio=Math.max(1,Math.min(2,devicePixelRatio||1));tile.width=256*ratio;tile.height=256*ratio;tile.style.width='256px';tile.style.height='256px';const ctx=tile.getContext('2d');ctx.scale(ratio,ratio);this._getDecodedTile(coords.z,coords.x,coords.y).then(features=>{this._paint(ctx,256,features);done(null,tile);}).catch(err=>done(err,tile));return tile;}
  _paint(ctx,size,features){for(const f of features){const p=f.properties||{};const province=p.level==='province';const selected=this.selectedIds.has(String(p.id));ctx.beginPath();for(const ring of f.geometry){if(!ring.length)continue;for(let i=0;i<ring.length;i++){const x=ring[i].x/f.extent*size,y=ring[i].y/f.extent*size;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();}ctx.fillStyle=selected?'rgba(255,218,57,.58)':province?'rgba(190,35,51,.075)':'rgba(20,103,186,.055)';ctx.fill('evenodd');ctx.strokeStyle=selected?'#df352f':province?'#bd2333':'#1467ba';ctx.lineWidth=selected?2.8:province?1.4:.75;ctx.globalAlpha=selected?1:.92;ctx.stroke();ctx.globalAlpha=1;}}
  setSelected(ids=[]){this.selectedIds=new Set(ids.map(String));this.redraw();}
  async featureAt(latlng,mapZoom,map){const z=Math.min(9,Math.max(4,Math.round(mapZoom)));const projected=map.project(latlng,z);const x=Math.floor(projected.x/256),y=Math.floor(projected.y/256);const features=await this._getDecodedTile(z,x,y);if(!features.length)return null;const extent=features[0].extent;const lx=(projected.x-x*256)/256*extent,ly=(projected.y-y*256)/256*extent;for(let i=features.length-1;i>=0;i--)if(pointInGeometry(lx,ly,features[i].geometry))return features[i];return null;}
}

async function loadBoundary(){
  const status=$('mapStatus');
  try{
    const html=await fetch(ANHMAP_SNAPSHOT,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(`anhmap ${r.status}`);return r.text();});
    const doc=new DOMParser().parseFromString(html,'text/html');
    const pm=doc.getElementById('pmtilesData'), ad=doc.getElementById('adminData');
    if(!pm||!ad)throw new Error('Không tìm thấy pmtilesData/adminData trong snapshot anhmap.');
    const archive=new PMTiles(new MemorySource(decodeBase64(pm.textContent)));
    const payload=JSON.parse(ad.textContent);state.boundaryRecords=payload.records||[];
    for(const r of state.boundaryRecords){state.boundaryByKey.set(unitKey(r.name,r.type,r.province),r);}
    state.boundary=new BoundaryLayer(archive,{attribution:'Ranh giới: Vietflexmap/anhmap'}).addTo(map);
    status.innerHTML='<span class="dot"></span><span>Ranh giới PMTiles sẵn sàng</span>';
  }catch(err){console.error(err);status.innerHTML='<span class="dot error"></span><span>Không nạp được ranh giới · dữ liệu tra cứu vẫn hoạt động</span>';}
}

const map=V.vietflexMap('map',{useLegacyGoogleTiles:true,googleMapType:'roadmap',zoomControl:false,attributionControl:false,center:[16.1,106.4],zoom:5,minZoom:4,maxZoom:18});
new V.ZoomControl({position:'topright'}).addTo(map);
new V.AttributionControl({position:'bottomright'}).addTo(map);
map.on('click',async e=>{if(!state.boundary)return;const f=await state.boundary.featureAt(e.latlng,map.getZoom(),map);if(!f)return;const rec=state.boundaryRecords.find(r=>String(r.id)===String(f.properties.id));if(!rec)return;const u=state.units.find(x=>unitKey(x.name,x.type,x.province_name)===unitKey(rec.name,rec.type,rec.province));if(u)selectItem(u,{openPopupAt:e.latlng});});

async function loadData(){const r=await fetch('./data/admin.json.gz');if(!r.ok)throw new Error(`data ${r.status}`);if(!('DecompressionStream' in window))throw new Error('Trình duyệt chưa hỗ trợ DecompressionStream.');const stream=r.body.pipeThrough(new DecompressionStream('gzip'));state.data=await new Response(stream).json();state.units=state.data.units;state.provinces=state.data.provinces;populateFilters();applyFilters();}
function populateFilters(){const s=$('provinceFilter');for(const p of state.provinces){const o=document.createElement('option');o.value=p.order;o.textContent=`${String(p.order).padStart(2,'0')} · ${p.full_name}`;s.appendChild(o);}}
function filteredUnits(){const p=Number($('provinceFilter').value)||null,t=$('typeFilter').value;return state.units.filter(u=>(!p||u.province_order===p)&&(!t||u.type===t));}
function applyFilters(){const rows=filteredUnits();renderList(rows.slice(0,300),rows.length);}
function renderList(rows,total){$('resultCount').textContent=`${fmt0.format(total)} đơn vị`;const el=$('unitList');el.innerHTML='';for(const u of rows){const b=document.createElement('button');b.className='unit-item'+(state.selected?.id===u.id?' active':'');b.innerHTML=`<strong>${escapeHtml(u.full_name)}</strong><small><span>${escapeHtml(u.province_name)}</span><code>${u.code}</code></small>`;b.onclick=()=>selectItem(u);el.appendChild(b);}if(total>300){const note=document.createElement('div');note.className='empty-state';note.innerHTML=`Đang hiển thị 300/${fmt0.format(total)}. Dùng tìm kiếm hoặc bộ lọc để thu hẹp.`;el.appendChild(note);}}
function provinceDetail(p){return `<div class="detail-head"><span class="badge">${escapeHtml(p.type)}</span><h2>${escapeHtml(p.full_name)}</h2><div class="detail-sub">${p.commune_level_count} đơn vị cấp xã · ${escapeHtml(p.resolution||'')}</div></div><div class="stats-grid"><div><span>Diện tích</span><b>${n(p.area_km2,2)} km²</b></div><div><span>Dân số</span><b>${n(p.population_2025)}</b></div><div><span>Mật độ</span><b>${n(p.density)}</b></div></div><div class="detail-body"><div class="detail-row"><b>Cơ cấu</b>${p.counts_by_type['phường']||0} phường · ${p.counts_by_type['xã']||0} xã · ${p.counts_by_type['đặc khu']||0} đặc khu</div><div class="detail-row"><b>Nguồn hình thành</b>${escapeHtml(p.merge_origin||'—')}</div></div><div class="detail-actions"><button class="secondary-btn" data-compare="${p.id}">+ So sánh</button></div>`;}
function unitDetail(u){return `<div class="detail-head"><span class="badge">${escapeHtml(u.type)}</span><h2>${escapeHtml(u.full_name)}</h2><div class="detail-sub">${escapeHtml(u.province_full_name)} · Mã ĐVHC ${u.code}</div></div><div class="stats-grid"><div><span>Diện tích</span><b>${n(u.area_km2,2)} km²</b></div><div><span>Dân số 2025</span><b>${n(u.population_2025)}</b></div><div><span>Mật độ</span><b>${n(u.density)}</b></div></div><div class="detail-body"><div class="detail-row"><b>Trung tâm hành chính</b>${escapeHtml(u.administrative_center||'—')}</div><div class="detail-row"><b>Được sắp xếp từ</b>${escapeHtml(u.merged_from||'—')}</div></div><div class="detail-actions"><button class="secondary-btn" data-compare="${u.id}">+ So sánh</button></div>`;}
function selectItem(item,opts={}){state.selected=item;const card=$('detailCard');card.classList.remove('empty');card.innerHTML=item.id.startsWith('p:')?provinceDetail(item):unitDetail(item);const compareBtn=card.querySelector('[data-compare]');if(compareBtn)compareBtn.onclick=()=>{openCompare(item.id.startsWith('p:')?'province':'unit');addCompare(item);};if(item.id.startsWith('u:')&&state.boundary){const rec=state.boundaryByKey.get(unitKey(item.name,item.type,item.province_name));state.boundary.setSelected(rec?[rec.id]:[]);}const rows=filteredUnits();renderList(rows.slice(0,300),rows.length);if(opts.openPopupAt){map.openPopup(`<b>${escapeHtml(item.full_name)}</b><br>Mã ${item.code}<br>${n(item.area_km2,2)} km² · ${n(item.population_2025)} người`,opts.openPopupAt);}if(innerWidth<=800)$('sidebar').classList.add('open');}

function search(q){const z=normalize(q);if(!z)return[];const exactCode=state.units.filter(u=>u.code===q.trim());const units=state.units.filter(u=>normalize(`${u.full_name} ${u.name} ${u.province_name} ${u.code}`).includes(z)).slice(0,18);const prov=state.provinces.filter(p=>normalize(`${p.full_name} ${p.name}`).includes(z)).slice(0,6);return [...prov,...exactCode,...units.filter(u=>!exactCode.includes(u))].slice(0,24);}
function showSearch(){const q=$('searchInput').value.trim(),box=$('searchResults');if(!q){box.hidden=true;return;}const rows=search(q);box.innerHTML=rows.length?rows.map(x=>`<button class="search-hit" data-id="${x.id}"><span><b>${escapeHtml(x.full_name)}</b><span>${x.id.startsWith('p:')?`${x.commune_level_count} đơn vị cấp xã`:escapeHtml(x.province_name)}</span></span>${x.code?`<code>${x.code}</code>`:''}</button>`).join(''):'<div class="empty-state">Không tìm thấy đơn vị phù hợp.</div>';box.hidden=false;box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const item=[...state.provinces,...state.units].find(x=>x.id===b.dataset.id);selectItem(item);box.hidden=true;});}

function openCompare(mode=state.compareMode){state.compareMode=mode;$('compareDrawer').classList.add('open');$('compareDrawer').setAttribute('aria-hidden','false');$('drawerBackdrop').hidden=false;document.querySelectorAll('.compare-mode button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));state.compareItems=state.compareItems.filter(x=>(mode==='province')===x.id.startsWith('p:'));renderCompare();}
function closeCompare(){$('compareDrawer').classList.remove('open');$('compareDrawer').setAttribute('aria-hidden','true');$('drawerBackdrop').hidden=true;}
function addCompare(item){if(state.compareItems.some(x=>x.id===item.id)||state.compareItems.length>=8)return;state.compareItems.push(item);renderCompare();}
function renderCompare(){const pool=state.compareMode==='province'?state.provinces:state.units;$('compareChips').innerHTML=state.compareItems.map(x=>`<span class="compare-chip">${escapeHtml(x.full_name)}<button data-remove="${x.id}">×</button></span>`).join('');$('compareChips').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.compareItems=state.compareItems.filter(x=>x.id!==b.dataset.remove);renderCompare();});const labels=state.compareItems.map(x=>x.full_name),values=state.compareItems.map(x=>Number(x[state.compareMetric])||0);const metricMeta={area_km2:['Diện tích','km²'],population_2025:['Dân số','người'],density:['Mật độ','người/km²']}[state.compareMetric];if(state.chart)state.chart.destroy();state.chart=new Chart($('compareChart'),{type:'bar',data:{labels,datasets:[{label:`${metricMeta[0]} (${metricMeta[1]})`,data:values,borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:labels.length>4?'y':'x',plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${metricMeta[0]}: ${fmt2.format(c.raw)} ${metricMeta[1]}`}}},scales:{y:{beginAtZero:true},x:{beginAtZero:true}}}});$('compareTable').innerHTML=state.compareItems.length?`<table><thead><tr><th>Đơn vị</th><th>Diện tích km²</th><th>Dân số</th><th>Mật độ</th></tr></thead><tbody>${state.compareItems.map(x=>`<tr><td>${escapeHtml(x.full_name)}</td><td>${n(x.area_km2,2)}</td><td>${n(x.population_2025)}</td><td>${n(x.density)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Thêm 2–8 đơn vị để so sánh.</div>';const q=normalize($('compareSearch').value);const sugg=q?pool.filter(x=>normalize(`${x.full_name} ${x.name||''} ${x.province_name||''} ${x.code||''}`).includes(q)&&!state.compareItems.some(y=>y.id===x.id)).slice(0,12):[];$('compareSuggestions').innerHTML=sugg.map(x=>`<button data-add="${x.id}"><b>${escapeHtml(x.full_name)}</b>${x.province_name?` · ${escapeHtml(x.province_name)}`:''}</button>`).join('');$('compareSuggestions').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const item=pool.find(x=>x.id===b.dataset.add);addCompare(item);$('compareSearch').value='';renderCompare();});}

$('provinceFilter').onchange=applyFilters;$('typeFilter').onchange=applyFilters;$('searchInput').oninput=showSearch;$('searchInput').onkeydown=e=>{if(e.key==='Escape')$('searchResults').hidden=true;};$('searchClear').onclick=()=>{$('searchInput').value='';$('searchResults').hidden=true;};$('compareOpen').onclick=()=>openCompare();$('compareClose').onclick=closeCompare;$('drawerBackdrop').onclick=closeCompare;$('compareSearch').oninput=renderCompare;$('sidebarToggle').onclick=()=>$('sidebar').classList.toggle('open');document.querySelectorAll('.compare-mode button').forEach(b=>b.onclick=()=>openCompare(b.dataset.mode));document.querySelectorAll('.metric-tabs button').forEach(b=>b.onclick=()=>{state.compareMetric=b.dataset.metric;document.querySelectorAll('.metric-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderCompare();});document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))$('searchResults').hidden=true;});

Promise.all([loadData(),loadBoundary()]).catch(err=>{console.error(err);$('mapStatus').innerHTML='<span class="dot error"></span><span>Lỗi khởi tạo dữ liệu</span>';});
